name: nt_commentaries
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.11.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.0
  google_fonts: ^8.0.2
  google_mobile_ads: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/web.json
    - assets/commentaries_json/clarke/Acts/
    - assets/commentaries_json/clarke/Colossians/
    - assets/commentaries_json/clarke/Ephesians/
    - assets/commentaries_json/clarke/Galatians/
    - assets/commentaries_json/clarke/Hebrews/
    - assets/commentaries_json/clarke/James/
    - assets/commentaries_json/clarke/John/
    - assets/commentaries_json/clarke/Jude/
    - assets/commentaries_json/clarke/Luke/
    - assets/commentaries_json/clarke/Mark/
    - assets/commentaries_json/clarke/Matthew/
    - assets/commentaries_json/clarke/Philemon/
    - assets/commentaries_json/clarke/Philippians/
    - assets/commentaries_json/clarke/Revelation/
    - assets/commentaries_json/clarke/Romans/
    - assets/commentaries_json/clarke/Titus/
    - assets/commentaries_json/clarke/1 Corinthians/
    - assets/commentaries_json/clarke/1 John/
    - assets/commentaries_json/clarke/1 Peter/
    - assets/commentaries_json/clarke/1 Thessalonians/
    - assets/commentaries_json/clarke/1 Timothy/
    - assets/commentaries_json/clarke/2 Corinthians/
    - assets/commentaries_json/clarke/2 John/
    - assets/commentaries_json/clarke/2 Peter/
    - assets/commentaries_json/clarke/2 Thessalonians/
    - assets/commentaries_json/clarke/2 Timothy/
    - assets/commentaries_json/clarke/3 John/
    - assets/commentaries_json/jfb/Acts/
    - assets/commentaries_json/jfb/Colossians/
    - assets/commentaries_json/jfb/Ephesians/
    - assets/commentaries_json/jfb/Galatians/
    - assets/commentaries_json/jfb/Hebrews/
    - assets/commentaries_json/jfb/James/
    - assets/commentaries_json/jfb/John/
    - assets/commentaries_json/jfb/Jude/
    - assets/commentaries_json/jfb/Luke/
    - assets/commentaries_json/jfb/Mark/
    - assets/commentaries_json/jfb/Matthew/
    - assets/commentaries_json/jfb/Philemon/
    - assets/commentaries_json/jfb/Philippians/
    - assets/commentaries_json/jfb/Revelation/
    - assets/commentaries_json/jfb/Romans/
    - assets/commentaries_json/jfb/Titus/
    - assets/commentaries_json/jfb/1 Corinthians/
    - assets/commentaries_json/jfb/1 John/
    - assets/commentaries_json/jfb/1 Peter/
    - assets/commentaries_json/jfb/1 Thessalonians/
    - assets/commentaries_json/jfb/1 Timothy/
    - assets/commentaries_json/jfb/2 Corinthians/
    - assets/commentaries_json/jfb/2 John/
    - assets/commentaries_json/jfb/2 Peter/
    - assets/commentaries_json/jfb/2 Thessalonians/
    - assets/commentaries_json/jfb/2 Timothy/
    - assets/commentaries_json/jfb/3 John/
    - assets/commentaries_json/rwp/Acts/
    - assets/commentaries_json/rwp/Colossians/
    - assets/commentaries_json/rwp/Ephesians/
    - assets/commentaries_json/rwp/Galatians/
    - assets/commentaries_json/rwp/Hebrews/
    - assets/commentaries_json/rwp/James/
    - assets/commentaries_json/rwp/John/
    - assets/commentaries_json/rwp/Jude/
    - assets/commentaries_json/rwp/Luke/
    - assets/commentaries_json/rwp/Mark/
    - assets/commentaries_json/rwp/Matthew/
    - assets/commentaries_json/rwp/Philemon/
    - assets/commentaries_json/rwp/Philippians/
    - assets/commentaries_json/rwp/Revelation/
    - assets/commentaries_json/rwp/Romans/
    - assets/commentaries_json/rwp/Titus/
    - assets/commentaries_json/rwp/1 Corinthians/
    - assets/commentaries_json/rwp/1 John/
    - assets/commentaries_json/rwp/1 Peter/
    - assets/commentaries_json/rwp/1 Thessalonians/
    - assets/commentaries_json/rwp/1 Timothy/
    - assets/commentaries_json/rwp/2 Corinthians/
    - assets/commentaries_json/rwp/2 John/
    - assets/commentaries_json/rwp/2 Peter/
    - assets/commentaries_json/rwp/2 Thessalonians/
    - assets/commentaries_json/rwp/2 Timothy/
    - assets/commentaries_json/rwp/3 John/
    - assets/commentaries_json/mhcc/Acts/
    - assets/commentaries_json/mhcc/Colossians/
    - assets/commentaries_json/mhcc/Ephesians/
    - assets/commentaries_json/mhcc/Galatians/
    - assets/commentaries_json/mhcc/Hebrews/
    - assets/commentaries_json/mhcc/James/
    - assets/commentaries_json/mhcc/John/
    - assets/commentaries_json/mhcc/Jude/
    - assets/commentaries_json/mhcc/Luke/
    - assets/commentaries_json/mhcc/Mark/
    - assets/commentaries_json/mhcc/Matthew/
    - assets/commentaries_json/mhcc/Philemon/
    - assets/commentaries_json/mhcc/Philippians/
    - assets/commentaries_json/mhcc/Revelation/
    - assets/commentaries_json/mhcc/Romans/
    - assets/commentaries_json/mhcc/Titus/
    - assets/commentaries_json/mhcc/1 Corinthians/
    - assets/commentaries_json/mhcc/1 John/
    - assets/commentaries_json/mhcc/1 Peter/
    - assets/commentaries_json/mhcc/1 Thessalonians/
    - assets/commentaries_json/mhcc/1 Timothy/
    - assets/commentaries_json/mhcc/2 Corinthians/
    - assets/commentaries_json/mhcc/2 John/
    - assets/commentaries_json/mhcc/2 Peter/
    - assets/commentaries_json/mhcc/2 Thessalonians/
    - assets/commentaries_json/mhcc/2 Timothy/
    - assets/commentaries_json/mhcc/3 John/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: true
  image_path: 'assets/NT_icon.png'
  adaptive_icon_background: '#2F6B33'
